export const STORAGE_TOKEN = 'STORAGE_TOKEN'
export const STORAGE_USERNAME = 'STORAGE_USERNAME'
export const STORAGE_USER_INFO = 'STORAGE_USER_INFO'
export const STORAGE_LOCALE_KEY = 'STORAGE_LOCALE_KEY'
